-- 1. Create Customers Table
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL
);

-- 2. Create an index on phone numbers to make lookups fast
CREATE INDEX idx_customers_phone ON customers(phone);

-- 3. Create Invoices Table
CREATE TABLE invoices (
    id TEXT PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE NOT NULL,
    invoice_date TIMESTAMP WITH TIME ZONE NOT NULL,
    total_amount NUMERIC(12, 2) NOT NULL,
    status TEXT DEFAULT 'Paid'
);

-- 4. Create Invoice Items Table
CREATE TABLE invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id TEXT REFERENCES invoices(id) ON DELETE CASCADE NOT NULL,
    product_name TEXT NOT NULL,
    quantity INT NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL
);